export const projects = [
  {
    id: 1,
    title: "Department Introductory",
    description: "Full-stack e-commerce solution with React and Node.js",
    longDescription:
      "A comprehensive department website built with modern technologies.",
    tech: ["React", "Node.js", "MongoDB", "Express"],
    category: "fullstack",
    image: "/projects/department.png",
    github: "https://github.com/ahsaulhoqueabir/csejnu",
    demo: "",
    stars: 0,
    forks: 0,
    status: "completed",
    featured: true,
    date: "2024-01-15",
    gradient: "from-blue-500/20 to-indigo-500/20",
    accentColor: "text-blue-500",
    orb: "bg-blue-500/30",
    topBar: "from-blue-500 to-indigo-500",
  },
  {
    id: 2,
    title: "Briefly60",
    description:
      "This is a summarized website for news and articles. It will help you to get the summary of top newspaper of Bangladesh in 60 words.",
    longDescription:
      "A news summarization platform that provides concise 60-word summaries of Bangladesh's top newspapers.",
    tech: ["Next.js", "TypeScript", "Prisma", "Socket.io"],
    category: "fullstack",
    image: "/projects/briefly60.png",
    github: "https://github.com/ahsaulhoqueabir/briefly60",
    demo: "https://briefly60.netlify.app/",
    stars: 0,
    forks: 0,
    status: "completed",
    featured: true,
    date: "2024-02-01",
    gradient: "from-emerald-500/20 to-teal-500/20",
    accentColor: "text-emerald-500",
    orb: "bg-emerald-500/30",
    topBar: "from-emerald-500 to-teal-500",
  },
  {
    id: 3,
    title: "IEEE JnU Student Chapter",
    description:
      "This is a website for IEEE JnU.It is used to manage the members and events update of IEEE JnU.",
    longDescription:
      "A website for managing IEEE JnU members and events, built with modern web technologies.",
    tech: ["NEXTjs", "Supabase", "Tailwind CSS", "Framer"],
    category: "frontend",
    image: "/projects/ieee.png",
    github: "https://github.com/ahsaulhoqueabir/ieeejnu",
    demo: "https://ieeejnu.vercel.app/",
    stars: 0,
    forks: 0,
    status: "completed",
    featured: true,
    date: "2024-01-20",
    gradient: "from-amber-500/20 to-orange-500/20",
    accentColor: "text-amber-500",
    orb: "bg-amber-500/30",
    topBar: "from-amber-500 to-orange-500",
  },
  {
    id: 4,
    title: "TEDxJagannathUniversity",
    description:
      "A website for TEDxJagannathUniversity, showcasing events and speakers.",
    longDescription:
      "A modern website for TEDxJagannathUniversity, featuring event details and speaker profiles.",
    tech: ["Next.js", "TypeScript", "Prisma", "Socket.io"],
    category: "fullstack",
    image: "/placeholder.jpg",
    github: "https://github.com/ahsanulhoqueabir/tedxjnu",
    stars: 0,
    forks: 0,
    status: "on-going",
    featured: true,
    date: "2025-04-25",
    gradient: "from-red-500/20 to-rose-500/20",
    accentColor: "text-red-500",
    orb: "bg-red-500/30",
    topBar: "from-red-500 to-rose-500",
  },
  {
    id: 5,
    title: "Bangladesh AI institute",
    description:
      "A website for Bangladesh AI Institute, providing information about courses and events.",
    longDescription:
      "A comprehensive website for Bangladesh AI Institute, showcasing courses, events, and resources.",
    tech: ["Next.js", "TypeScript", "Prisma", "Socket.io"],
    category: "fullstack",
    image: "/placeholder.jpg",
    github: "https://github.com/ahsanulhoqueabir/bangladesh-ai-institute",
    stars: 0,
    forks: 0,
    status: "completed",
    featured: false,
    date: "2025-05-20",
    gradient: "from-violet-500/20 to-purple-500/20",
    accentColor: "text-violet-500",
    orb: "bg-violet-500/30",
    topBar: "from-violet-500 to-purple-500",
  },
];
