export const projectsSeed = [
  {
    projectId: 1,
    title: "Department Introductory",
    description: "Full-stack e-commerce solution with React and Node.js",
    longDescription:
      "A comprehensive department website built with modern technologies.",
    tech: ["React", "Node.js", "MongoDB", "Express"],
    category: "fullstack",
    images: ["/projects/department.png"],
    github: "https://github.com/ahsaulhoqueabir/csejnu",
    demo: "",
    stars: 0,
    forks: 0,
    status: "completed",
    featured: true,
    publishedAt: new Date("2024-01-15"),
    gradientClass: "from-blue-500/20 to-indigo-500/20",
    accentColorClass: "text-blue-500",
    orbClass: "bg-blue-500/30",
    topBarClass: "from-blue-500 to-indigo-500",
    isActive: true,
  },
  {
    projectId: 2,
    title: "Briefly60",
    description:
      "This is a summarized website for news and articles. It will help you to get the summary of top newspaper of Bangladesh in 60 words.",
    longDescription:
      "A news summarization platform that provides concise 60-word summaries of Bangladesh's top newspapers.",
    tech: ["Next.js", "TypeScript", "Prisma", "Socket.io"],
    category: "fullstack",
    images: ["/projects/briefly60.png"],
    github: "https://github.com/ahsaulhoqueabir/briefly60",
    demo: "https://briefly60.netlify.app/",
    stars: 0,
    forks: 0,
    status: "completed",
    featured: true,
    publishedAt: new Date("2024-02-01"),
    gradientClass: "from-emerald-500/20 to-teal-500/20",
    accentColorClass: "text-emerald-500",
    orbClass: "bg-emerald-500/30",
    topBarClass: "from-emerald-500 to-teal-500",
    isActive: true,
  },
  {
    projectId: 3,
    title: "IEEE JnU Student Chapter",
    description:
      "This is a website for IEEE JnU.It is used to manage the members and events update of IEEE JnU.",
    longDescription:
      "A website for managing IEEE JnU members and events, built with modern web technologies.",
    tech: ["NEXTjs", "Supabase", "Tailwind CSS", "Framer"],
    category: "frontend",
    images: ["/projects/ieee.png"],
    github: "https://github.com/ahsaulhoqueabir/ieeejnu",
    demo: "https://ieeejnu.vercel.app/",
    stars: 0,
    forks: 0,
    status: "completed",
    featured: true,
    publishedAt: new Date("2024-01-20"),
    gradientClass: "from-amber-500/20 to-orange-500/20",
    accentColorClass: "text-amber-500",
    orbClass: "bg-amber-500/30",
    topBarClass: "from-amber-500 to-orange-500",
    isActive: true,
  },
  {
    projectId: 4,
    title: "TEDxJagannathUniversity",
    description:
      "A website for TEDxJagannathUniversity, showcasing events and speakers.",
    longDescription:
      "A modern website for TEDxJagannathUniversity, featuring event details and speaker profiles.",
    tech: ["Next.js", "TypeScript", "Prisma", "Socket.io"],
    category: "fullstack",
    images: ["/placeholder.jpg"],
    github: "https://github.com/ahsanulhoqueabir/tedxjnu",
    demo: "",
    stars: 0,
    forks: 0,
    status: "on-going",
    featured: true,
    publishedAt: new Date("2025-04-25"),
    gradientClass: "from-red-500/20 to-rose-500/20",
    accentColorClass: "text-red-500",
    orbClass: "bg-red-500/30",
    topBarClass: "from-red-500 to-rose-500",
    isActive: true,
  },
  {
    projectId: 5,
    title: "Bangladesh AI institute",
    description:
      "A website for Bangladesh AI Institute, providing information about courses and events.",
    longDescription:
      "A comprehensive website for Bangladesh AI Institute, showcasing courses, events, and resources.",
    tech: ["Next.js", "TypeScript", "Prisma", "Socket.io"],
    category: "fullstack",
    images: ["/placeholder.jpg"],
    github: "https://github.com/ahsanulhoqueabir/bangladesh-ai-institute",
    demo: "",
    stars: 0,
    forks: 0,
    status: "completed",
    featured: false,
    publishedAt: new Date("2025-05-20"),
    gradientClass: "from-violet-500/20 to-purple-500/20",
    accentColorClass: "text-violet-500",
    orbClass: "bg-violet-500/30",
    topBarClass: "from-violet-500 to-purple-500",
    isActive: true,
  },
];
