export const skillsContentSeed = {
  slug: "default",
  isActive: true,
  categories: [
    {
      key: "frontend",
      title: "Frontend Development",
      images: ["/images/categories/frontend-development.svg"],
      colorFrom: "from-blue-500",
      colorTo: "to-cyan-500",
      order: 1,
      skills: [
        {
          name: "React",
          level: 95,
          experienceYears: 3,
          images: ["/images/skills/react.svg"],
        },
        {
          name: "Next.js",
          level: 90,
          experienceYears: 3,
          images: ["/images/skills/nextjs.svg"],
        },
        {
          name: "TypeScript",
          level: 88,
          experienceYears: 3,
          images: ["/images/skills/typescript.svg"],
        },
        {
          name: "JavaScript",
          level: 92,
          experienceYears: 3,
          images: ["/images/skills/javascript.svg"],
        },
        {
          name: "HTML5",
          level: 96,
          experienceYears: 3,
          images: ["/images/skills/html5.svg"],
        },
        {
          name: "CSS3",
          level: 90,
          experienceYears: 3,
          images: ["/images/skills/css3.svg"],
        },
        {
          name: "Tailwind CSS",
          level: 85,
          experienceYears: 2,
          images: ["/images/skills/tailwind.svg"],
        },
        {
          name: "Sass/SCSS",
          level: 80,
          experienceYears: 3,
          images: ["/images/skills/sass.svg"],
        },
        {
          name: "Framer Motion",
          level: 78,
          experienceYears: 2,
          images: ["/images/skills/framer.svg"],
        },
      ],
    },
    {
      key: "backend",
      title: "Backend Development",
      images: ["/images/categories/backend-development.svg"],
      colorFrom: "from-green-500",
      colorTo: "to-emerald-500",
      order: 2,
      skills: [
        {
          name: "Node.js",
          level: 85,
          experienceYears: 3,
          images: ["/images/skills/nodejs.svg"],
        },
        {
          name: "Express.js",
          level: 82,
          experienceYears: 3,
          images: ["/images/skills/express.svg"],
        },
        {
          name: "GraphQL",
          level: 72,
          experienceYears: 2,
          images: ["/images/skills/graphql.svg"],
        },
        {
          name: "REST APIs",
          level: 88,
          experienceYears: 3,
          images: ["/images/skills/rest-api.svg"],
        },
        {
          name: "Socket.io",
          level: 70,
          experienceYears: 2,
          images: ["/images/skills/socket-io.svg"],
        },
        {
          name: "Microservices",
          level: 68,
          experienceYears: 2,
          images: ["/images/skills/microservices.svg"],
        },
        {
          name: "Serverless",
          level: 65,
          experienceYears: 1,
          images: ["/images/skills/serverless.svg"],
        },
      ],
    },
    {
      key: "database",
      title: "Database & Storage",
      images: ["/images/categories/database-storage.svg"],
      colorFrom: "from-purple-500",
      colorTo: "to-pink-500",
      order: 3,
      skills: [
        {
          name: "PostgreSQL",
          level: 78,
          experienceYears: 3,
          images: ["/images/skills/postgresql.svg"],
        },
        {
          name: "MongoDB",
          level: 80,
          experienceYears: 3,
          images: ["/images/skills/mongodb.svg"],
        },
        {
          name: "MySQL",
          level: 75,
          experienceYears: 3,
          images: ["/images/skills/mysql.svg"],
        },
        {
          name: "Redis",
          level: 70,
          experienceYears: 2,
          images: ["/images/skills/redis.svg"],
        },
        {
          name: "Prisma",
          level: 75,
          experienceYears: 2,
          images: ["/images/skills/prisma.svg"],
        },
        {
          name: "Mongoose",
          level: 78,
          experienceYears: 3,
          images: ["/images/skills/mongoose.svg"],
        },
        {
          name: "SQLite",
          level: 72,
          experienceYears: 2,
          images: ["/images/skills/sqlite.svg"],
        },
        {
          name: "Firebase",
          level: 68,
          experienceYears: 2,
          images: ["/images/skills/firebase.svg"],
        },
        {
          name: "Supabase",
          level: 65,
          experienceYears: 1,
          images: ["/images/skills/supabase.svg"],
        },
      ],
    },
    {
      key: "tools",
      title: "Tools & DevOps",
      images: ["/images/categories/tools-devops.svg"],
      colorFrom: "from-orange-500",
      colorTo: "to-red-500",
      order: 4,
      skills: [
        {
          name: "Git",
          level: 90,
          experienceYears: 3,
          images: ["/images/skills/git.svg"],
        },
        {
          name: "Docker",
          level: 75,
          experienceYears: 2,
          images: ["/images/skills/docker.svg"],
        },
        {
          name: "AWS",
          level: 70,
          experienceYears: 2,
          images: ["/images/skills/aws.svg"],
        },
        {
          name: "Vercel",
          level: 85,
          experienceYears: 3,
          images: ["/images/skills/vercel.svg"],
        },
        {
          name: "Netlify",
          level: 80,
          experienceYears: 2,
          images: ["/images/skills/netlify.svg"],
        },
        {
          name: "GitHub Actions",
          level: 72,
          experienceYears: 2,
          images: ["/images/skills/github-actions.svg"],
        },
        {
          name: "Webpack",
          level: 70,
          experienceYears: 3,
          images: ["/images/skills/webpack.svg"],
        },
        {
          name: "Vite",
          level: 78,
          experienceYears: 2,
          images: ["/images/skills/vite.svg"],
        },
      ],
    },
    {
      key: "mobile",
      title: "Mobile Development",
      images: ["/images/categories/mobile-development.svg"],
      colorFrom: "from-teal-500",
      colorTo: "to-cyan-500",
      order: 5,
      skills: [
        {
          name: "React Native",
          level: 72,
          experienceYears: 2,
          images: ["/images/skills/react-native.svg"],
        },
        {
          name: "Expo",
          level: 70,
          experienceYears: 2,
          images: ["/images/skills/expo.svg"],
        },
      ],
    },
    {
      key: "design",
      title: "Design & UI/UX",
      images: ["/images/categories/design-ui-ux.svg"],
      colorFrom: "from-pink-500",
      colorTo: "to-rose-500",
      order: 6,
      skills: [
        {
          name: "Figma",
          level: 80,
          experienceYears: 3,
          images: ["/images/skills/figma.svg"],
        },
        {
          name: "Photoshop",
          level: 65,
          experienceYears: 3,
          images: ["/images/skills/photoshop.svg"],
        },
        {
          name: "UI Design",
          level: 75,
          experienceYears: 3,
          images: ["/images/skills/ui-design.svg"],
        },
        {
          name: "UX Research",
          level: 68,
          experienceYears: 2,
          images: ["/images/skills/ux-research.svg"],
        },
        {
          name: "Prototyping",
          level: 72,
          experienceYears: 2,
          images: ["/images/skills/prototyping.svg"],
        },
        {
          name: "Responsive Design",
          level: 85,
          experienceYears: 3,
          images: ["/images/skills/responsive-design.svg"],
        },
        {
          name: "Accessibility",
          level: 70,
          experienceYears: 2,
          images: ["/images/skills/accessibility.svg"],
        },
      ],
    },
  ],
  stats: [
    {
      value: "8+",
      label: "Frontend Technologies",
      colorClass: "text-blue-500",
      backgroundClass: "bg-blue-500/10",
      borderClass: "border-blue-500/20",
    },
    {
      value: "6+",
      label: "Backend Technologies",
      colorClass: "text-emerald-500",
      backgroundClass: "bg-emerald-500/10",
      borderClass: "border-emerald-500/20",
    },
    {
      value: "8+",
      label: "Databases",
      colorClass: "text-violet-500",
      backgroundClass: "bg-violet-500/10",
      borderClass: "border-violet-500/20",
    },
    {
      value: "10+",
      label: "Tools & Platforms",
      colorClass: "text-amber-500",
      backgroundClass: "bg-amber-500/10",
      borderClass: "border-amber-500/20",
    },
  ],
  summaryItems: [
    {
      title: "Continuous Learning",
      description:
        "I stay updated with the latest technologies and best practices through online courses, documentation, and hands-on experimentation.",
      images: ["/images/summary/continuous-learning.svg"],
      gradientFrom: "from-blue-500",
      gradientTo: "to-cyan-500",
      backgroundClass: "bg-blue-500/10",
      imageTintClass: "text-blue-500",
    },
    {
      title: "Practical Application",
      description:
        "I believe in learning by doing. Every skill I acquire is immediately applied in real projects to solidify my understanding.",
      images: ["/images/summary/practical-application.svg"],
      gradientFrom: "from-amber-500",
      gradientTo: "to-orange-500",
      backgroundClass: "bg-amber-500/10",
      imageTintClass: "text-amber-500",
    },
    {
      title: "Knowledge Sharing",
      description:
        "I actively contribute to the developer community through blog posts, open-source contributions, and mentoring fellow developers.",
      images: ["/images/summary/knowledge-sharing.svg"],
      gradientFrom: "from-violet-500",
      gradientTo: "to-pink-500",
      backgroundClass: "bg-violet-500/10",
      imageTintClass: "text-violet-500",
    },
  ],
};
